# Generated by Django 5.2.13 on 2026-04-28 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: BL-01', max_length=50)),
                ('esta_activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('coordenadas_gps', models.CharField(help_text='Coordenadas GPS obligatorias', max_length=100)),
                ('comuna', models.CharField(max_length=100)),
                ('esta_activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('justificacion_desactivacion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Panel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: PA-01', max_length=50)),
                ('esta_activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paneles', to='gestion.bloque')),
            ],
        ),
        migrations.CreateModel(
            name='Simbolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: SIM-01', max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('iconografia', models.CharField(blank=True, max_length=150, null=True)),
                ('estado_conservacion', models.TextField(blank=True, null=True)),
                ('esta_activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simbolos', to='gestion.panel')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoMultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_archivo', models.CharField(choices=[('FOTO', 'Fotografía'), ('CALCO', 'Calco Digital')], max_length=10)),
                ('archivo', models.FileField(help_text='Soporta JPG, PNG, PDF. Max 50MB', upload_to='multimedia/')),
                ('es_principal', models.BooleanField(default=False, help_text='Marcar si es la imagen principal del símbolo')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('simbolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='gestion.simbolo')),
            ],
        ),
        migrations.AddField(
            model_name='bloque',
            name='sitio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='gestion.sitio'),
        ),
    ]
