# Generated by Django 5.2.13 on 2026-04-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_simbolo_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simbolo',
            name='estado_conservacion',
            field=models.CharField(blank=True, choices=[('BUENO', 'Bueno'), ('ACEPTABLE', 'Aceptable'), ('EN_RIESGO', 'En riesgo'), ('MALO', 'Malo'), ('SIN_DATOS', 'Sin evaluar')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='simbolo',
            name='iconografia',
            field=models.CharField(blank=True, help_text='Tipo o motivo representado (iconografia)', max_length=150, null=True),
        ),
    ]
